version: '3.1'

services:

  wordpress:

    image: wordpress

    restart: always

    ports:

      - 8080:80

    environment:

      WORDPRESS_DB_HOST: dbwordpress

      WORDPRESS_DB_USER: Haroon_test

      WORDPRESS_DB_PASSWORD: 12345678

      WORDPRESS_DB_NAME: exampledb

    volumes:

      - wordpress:/var/www/html

  db:

    image: mysql:8.0

    restart: always

    environment:

      MYSQL_DATABASE: wordpressdb

      MYSQL_USER: Haroon_test

      MYSQL_PASSWORD: 7654321

      MYSQL_RANDOM_ROOT_PASSWORD: '1'

    volumes:

      - db:/var/lib/mysql

volumes:

  wordpress:

  db:
